#!/usr/bin/env bash
# Renders a screenshot of every story checkpoint (data/scenarios.json) into docs/checkpoints/
# and writes docs/CHECKPOINTS.md — a one-page gallery of where the game is up to, for anyone
# who wants to see progress without playing.
#
#   tools/checkpoints.sh            # all checkpoints
#   tools/checkpoints.sh thornwold  # just these ids (the gallery page is always rewritten)
#
# Needs xvfb-run (screenshots use the OpenGL Compatibility renderer, which looks paler than the
# real Forward+ renderer). A checkpoint's optional "shot" field holds extra screenshot args
# (e.g. "--at=0,-11,0" or "--camera=x,y,z:tx,ty,tz"); see scripts/debug/screenshot.gd.
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GODOT="${GODOT:-$ROOT/.tools/bin/godot}"
OUT="$ROOT/docs/checkpoints"
mkdir -p "$OUT"
cd "$ROOT"

mapfile -t ROWS < <(python3 - "$@" <<'PY'
import json, sys
only = set(sys.argv[1:])
for s in json.load(open("data/scenarios.json"))["scenarios"]:
    if not only or s["id"] in only:
        print(s["id"] + "\t" + s.get("shot", ""))
PY
)
FAILED=0
for row in "${ROWS[@]}"; do
	id="${row%%$'\t'*}"
	shot="${row#*$'\t'}"
	echo "== $id"
	# shellcheck disable=SC2086
	if ! timeout 180 xvfb-run -a "$GODOT" --rendering-driver opengl3 --path . -- \
			--scenario="$id" $shot --settle=60 --screenshot="$OUT/$id.png" >"$OUT/.last.log" 2>&1; then
		echo "   FAILED — see $OUT/.last.log"
		FAILED=1
	fi
done
rm -f "$OUT/.last.log"

python3 - <<'PY'
import json, datetime, subprocess
data = json.load(open("data/scenarios.json"))["scenarios"]
rev = subprocess.run(["git", "rev-parse", "--short", "HEAD"], capture_output=True, text=True).stdout.strip()
lines = ["# Emberwake — Story checkpoints", "",
         "Where the game is up to, one screenshot per story checkpoint. Generated by",
         "`tools/checkpoints.sh` from `data/scenarios.json` (at commit `%s`, %s UTC)." % (rev, datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M")),
         "", "Play from any of them: `godot --path . -- --scenario=<id>`, or in a debug build open the",
         "pause menu (Esc) → **Chapter select (dev)**. `--scenario=list` prints them all.",
         "Screenshots come from the sandbox's Compatibility renderer and look paler than the game.", ""]
act = None
for s in data:
    if s["act"] != act:
        act = s["act"]
        lines += ["## " + act, ""]
    lines += ["### %s  (`--scenario=%s`)" % (s["title"], s["id"]), "", s["description"], "",
              "![%s](checkpoints/%s.png)" % (s["title"], s["id"]), ""]
open("docs/CHECKPOINTS.md", "w").write("\n".join(lines))
print("wrote docs/CHECKPOINTS.md")
PY
exit $FAILED
